:plantuml-server-url: https://www.plantuml.com/plantuml
:source-highlighter: highlightjs
:title-logo-image: image:./src/app.svg

= abaplint.app
Documentation
:toc:
:toclevels: 3
:numbered:

[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/docs.abaplint.app[https://github.com/heliconialabs/docs.abaplint.app]

|License
|link:https://github.com/heliconialabs/docs.abaplint.app/blob/main/LICENSE[Creative Commons]

|Build
|{docdatetime}
|===

== Introduction
abaplint.app is a cloud based tool for helping ABAP developers develop ABAP. The app can be used for static analysis and continuous integration, providing multiple configurable rules to support any development guidelines.

=== Requirements
A GitHub user or organization is required for use with the abaplint.app.
The latest version of link:https://abapgit.org[abapGit] is required for serializing the ABAP artifacts, abapGit works on SAP_BASIS 702 and up.

== Quick Start

. link:https://github.com/join[Create GitHub User or Organization]
. link:https://github.com/marketplace/abaplint[Install the app from the marketplace]
. link:https://docs.abapgit.org/guide-install.html[Install abapGit in the ABAP system]
. Push ABAP code to GitHub via abapGit

abaplint.app is automatically triggered for each commit or when a pull request is opened.

== Rule Configuration

abaplint is configured via `/abaplint.json` in the git repository, if no configuration file is present, the default configuration is used, which have all rules enabled.

The default configuration can be found on link:https://playground.abaplint.org[playground.abaplint.app], which can also help to test different configuration and findings.

If editing the configuration file via link:https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint[vscode abaplint extension], the editor will know the format of the json configuration file and help discovering and updating rule configuration.

link:https://rules.abaplint.org[rules.abaplint.org] lists and documents all rules which can be configured.

== ATC/SCI Integration
The ABAP developer can check the working copy in the ABAP system via link:https://github.com/abaplint/abaplint-sci-client[abaplint-sci-client]

<<<<

include::observations.adoc[]

<<<<

include::suggestions.adoc[]

<<<<

include::insights.adoc[]