:plantuml-server-url: https://www.plantuml.com/plantuml
:source-highlighter: highlightjs
:title-logo-image: image:./src/app.svg

= abaplint.app
Documentation
:toc:
:toclevels: 3
:numbered:

[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/docs.abaplint.app[https://github.com/heliconialabs/docs.abaplint.app]

|License
|link:https://github.com/heliconialabs/docs.abaplint.app/blob/main/LICENSE[Creative Commons]

|Build
|{docdatetime}
|===

== Introduction
abaplint.app is a cloud based tool for helping ABAP developers develop ABAP. The app can be used for static analysis and continuous integration, providing multiple configurable rules to support any development guidelines.

=== Requirements
A GitHub user or organization is required for use with the abaplint.app.
The latest version of link:https://abapgit.org[abapGit] is required for serializing the ABAP artifacts, abapGit works on SAP_BASIS 702 and up.

== Quick Start

. link:https://github.com/join[Create GitHub User or Organization]
. link:https://github.com/marketplace/abaplint[Install the app from the marketplace]
. link:https://docs.abapgit.org/guide-install.html[Install abapGit in the ABAP system]
. Push ABAP code to GitHub via abapGit

abaplint.app is automatically triggered for each commit or when a pull request is opened.

== Rule Configuration

abaplint is configured via a file `/abaplint.json` in the git repository, if no configuration file is present, the default configuration is used, which have all rules enabled.

The default configuration can be found on link:https://playground.abaplint.org[playground.abaplint.app], which can also help to test different configuration and findings.

If the link:https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint[vscode abaplint extension] is installed, the editor will know the format of the json configuration file and help discovering and updating rules.

link:https://rules.abaplint.org[rules.abaplint.org] lists and documents all rules which can be configured.

== ATC/SCI Integration
The ABAP developer can check the working copy in the ABAP system via link:https://github.com/abaplint/abaplint-sci-client[abaplint-sci-client]

== Observations

Observations are run only in the context of a pull request, and reports only "success" or "neutral" run status, so it will not block merges in case of link:https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging[required checks].

Implementation of observations is currently work in progress, and progress and impact can be seen in each pull request.

Like abaplint rules, there are multiple observations which can be enabled and disabled, these will be described in this document as implementation proceeds.